sudo: false

language: python

os:
    - linux
    - osx
    
python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    
install:
    - if [[ $TRAVIS_PYTHON_VERSION == 3.3 ]]; then pip install numpy==1.11; fi
    - pip install tox-travis

script: tox
